import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Forum | Ô Délices de Bertrand',
  description: 'Generated by create next app',
};

const Forum = () => {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-center uppercase text-3xl">Forum</p>
    </div>
  );
};

export default Forum;
