import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Contact | Les Gourmandises d'Olivier",
  description: 'Generated by create next app',
};

const Contact = () => {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-center uppercase text-3xl">Contact</p>
    </div>
  );
};

export default Contact;
