import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "À propos | Les Gourmandises d'Olivier",
  description: 'Generated by create next app',
};

const About = () => {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-center uppercase text-3xl">À propos</p>
    </div>
  );
};

export default About;
