import type { Metadata } from 'next';
import './about.scss';
import Image from 'next/image';
import Particles from './AboutParticles';

export const metadata: Metadata = {
  title: 'À propos | Ô Délices de Bertrand',
  description: 'Generated by create next app',
};

const About = () => {
  return (
    <>
      <section className="pt-[15dvh] lg:pt-[20dvh] px-10 lg:px-20 flex flex-col items-center lg:flex-row justify-around font-bold select-none">
        <div className="absolute">
          <Particles />
        </div>
        <div className="z-10 lg:w-1/2 lg:mx-16 mt-10 mb-14 lg:mb-10">
          <Image
            src="/assets/img/agent-card2.png"
            alt="Carte de l'agent culinaire Bertrand"
            width={700}
            height={400}
          />
        </div>
        <aside className="flex flex-col w-11/12 lg:w-1/2 handlee text-justify text-xl lg:text-2xl text-gray-600 z-10">
          <div className="border rounded-md p-5 lg:p-10 lg:w-4/5 mb-10 bg-[rgb(255,255,255,0.95)] agentCard transition duration-300 ease-in lg:hover:scale-125 hover:cursor-zoom-in">
            <p>
              Passionné par l&lsquo;art culinaire, et créateur d&lsquo;expériences
              gastronomiques authentiques, je mets mon savoir-faire au service de vos
              envies gustatives.
            </p>
          </div>
          <div className="border rounded-md p-5 lg:p-10 lg:mr-20 lg:mt-10 bg-[rgb(255,255,255,0.95)] agentCard transition duration-300 ease-in lg:hover:scale-125 hover:cursor-zoom-in">
            <p>
              <span className="text-orange-500 [text-shadow:_0.05vw_0.05vw_0.1vw_rgb(60,60,60)]">
                &ldquo;Sortez chez vous !&ldquo;
              </span>
              : ce slogan illustre mon appétit à vous faire vivre un moment particulier et
              mémorable, dans le confort de votre cocon familial.
            </p>
          </div>
        </aside>
      </section>
      <h2 className="w-4/5 lg:w-2/3 z-20 relative my-20 lg:my-48 handlee font-bold text-5xl lg:text-8xl m-auto text-center">
        À propos de Bertrand
      </h2>
      <section className="w-4/5 lg:w-2/3 z-20 relative bg-slate-300 m-auto p-10 text-justify">
        <div className="flex flex-col lg:flex-row">
          <Image
            src={'/assets/img/violoncelle.jpg'}
            width={300}
            height={150}
            alt="Bertrand qui joue du violoncelle à 8 ans"
          />
          <p className="lg:ml-8 mt-5 lg:mt-0">
            Ecole de musique, côté artiste blah blah Lorem ipsum dolor sit amet
            consectetur adipisicing elit. Pariatur est aliquam doloremque et ipsa
            molestias dignissimos ratione, voluptatum id maiores sed ex a iusto deleniti
            veniam? In ex a soluta? Hic odit saepe perferendis mollitia quo! Vel, alias
            ipsum velit cupiditate iure optio.
          </p>
        </div>
        <div className="flex flex-col-reverse lg:flex-row mt-12 lg:mt-28">
          <p className="mt-5 lg:mt-0 lg:mr-8">
            Avant d&lsquo;intégrer le lycée technologique de Gerardmer en 1995 puis celui
            de Toulouse en 1997 suite à un déménagement, Lorem ipsum dolor sit amet
            consectetur adipisicing elit. Pariatur est aliquam doloremque et ipsa
            molestias dignissimos ratione, voluptatum id maiores sed ex a iusto deleniti
            veniam? In ex a soluta? Hic odit saepe perferendis mollitia quo! Vel, alias
            ipsum velit cupiditate iure optio.
          </p>
          <Image
            src={'/assets/img/gateau.jpg'}
            width={300}
            height={150}
            alt="Bertrand qui joue du viloncelle à 8 ans"
          />
        </div>
      </section>
    </>
  );
};

export default About;
