import './globals.scss';
import type { Metadata } from 'next';
import Navbar from './components/Navbar2';

export const metadata: Metadata = {
  title: "Les Gourmandises d'Olivier",
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body suppressHydrationWarning={true}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
