import type { Metadata } from 'next';
import './page.scss';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Accueil | Ô Délices de Bertrand',
  description: 'Generated by create next app',
};

const Home = () => {
  return (
    <main className="bg-slate-400 bg-texture">
      <div className="absolute h-[30dvh] lg:h-[60dvh] w-full bg-white bg-texture"></div>
      <section className="h-[calc(100dvh-80px)] flex flex-col mt-[80px] w-[90%] mx-auto font-bold">
        <div
          className="
          main-title 
          handlee
          text-center 
          text-[1.5rem]
          md:text-[3rem] 
          lg:text-[3.5rem]
          m-auto
          "
        >
          <div className="w-4/5 lg:w-1/2 m-auto py-[calc(100dvh/15)]">
            <h1 className="text-3xl lg:text-6xl w-4/5 lg:w-full m-auto relative -top-20 lg:top-0 text-orange-500">
              Ô Délices de Bertrand
            </h1>
            <h2 className="text-amber-400 relative -top-20 pt-1 lg:top-0">
              Un chef dans votre cuisine
            </h2>
            <Image
              src={'/assets/img/chef-lutin.png'}
              width={1200}
              height={1097}
              alt="Coque en chocolat noir, crème fouettée au citron vert et fruits de saison"
              className="mt-5 relative"
            />
          </div>
        </div>
      </section>
    </main>
  );
};

export default Home;
