import type { Metadata } from 'next';
import Image from 'next/image';
import './page.scss';

export const metadata: Metadata = {
  title: 'Accueil | Ô Délices de Bertrand',
  description: 'Generated by create next app',
};

const Home = () => {
  return (
    <main className="">
      <section className="h-[calc(100dvh-80px)] flex flex-col mt-[80px] w-[90%] mx-auto font-bold">
        {/* h-[calc(100vh-74px)] */}
        <div
          className="
          main-title 
          cinzel
        text-orange-400
          text-center 
          text-[1.5rem]
          md:text-[3rem] 
          lg:text-[3.5rem]
          m-auto
          "
        >
          {/* <h1 className='cinzel text-orange-400'>
            Profitez de vos invités en toute tranquillité
          </h1> */}
          <h1>Site en cours de construction</h1>
          {/* <h2 className="mt-6 lg:mt-10">Le plaisir de recevoir !</h2> */}
          <div className="w-1/2 m-auto py-[calc(100vh/15)]">
            <Image
              src="/assets/img/gif-en-construction.gif"
              alt="Ouvrier qui creuse"
              width={300}
              height={300}
              className="m-auto"
            />
          </div>
          <div className="m-8 border-4 border-slate-600">
            <Image
              src="/assets/img/clafoutis-pommes.png"
              alt="clafoutis aux pommes"
              width={800}
              height={820}
            />
          </div>
          <h2 className="text-indigo-500">À bientôt !</h2>
        </div>
      </section>
    </main>
  );
};

export default Home;
