'use client';
import type { Metadata } from 'next';
import Image from 'next/image';
import './gallery.scss';
import { useCallback } from 'react';
import { PhotoAlbum, RenderPhotoProps } from 'react-photo-album';

/* export const metadata: Metadata = {
  title: "Galerie d'images | Ô Délices de Bertrand",
  description: 'Generated by create next app',
}; */

interface Img {
  src: number;
  alt: string;
  width: number;
  height: number;
}

const photo = [
  {
    src: '/assets/img/anniv2.jpg',
    alt: 'clafoutis aux pommes',
    width: 500,
    height: 667,
  },
  {
    src: '/assets/img/clafoutis.jpg',
    alt: 'clafoutis aux pommes',
    width: 500,
    height: 513,
  },
  {
    src: '/assets/img/truite.jpg',
    alt: 'clafoutis aux pommes',
    width: 800,
    height: 600,
  },
  {
    src: '/assets/img/dahl.jpg',
    alt: 'clafoutis aux pommes',
    width: 600,
    height: 800,
  },
  {
    src: '/assets/img/anniv.jpg',
    alt: 'clafoutis aux pommes',
    width: 500,
    height: 667,
  },
];

const Gallery = () => {
  const renderPhoto = useCallback(
    ({ imageProps: { alt, style, ...rest } }: RenderPhotoProps) => (
      <img
        alt={alt}
        style={{
          ...style,
          borderRadius: '1vw',
          boxShadow:
            '0px 3px 3px -2px rgb(0 0 0 / 20%), 0px 3px 4px 0px rgb(0 0 0 / 14%), 0px 1px 8px 0px rgb(0 0 0 / 12%)',
          backgroundColor: 'white',
        }}
        {...rest}
      />
    ),
    []
  );
  return (
    <main className="gallery-container select-none py-[15dvh]">
      <h2 className="font-bold text-center uppercase text-3xl">Gallerie</h2>
      <section className="my-10 w-2/3 m-auto">
        <PhotoAlbum
          layout="rows"
          photos={photo}
          spacing={30}
          padding={25}
          targetRowHeight={400}
          renderPhoto={renderPhoto}
        />
      </section>
    </main>
  );
};

export default Gallery;
