import type { Metadata } from 'next';
import ImageElt from './photosAlbum';

export const metadata: Metadata = {
  title: "Galerie d'images | Ô Délices de Bertrand",
  description: 'Generated by create next app',
};

const Gallery = () => {
  return (
    <main className="gallery-container handlee select-none py-[22dvh] lg:py-[20dvh]">
      <h2 className="font-bold text-center underline text-3xl">
        Gallerie d&lsquo;images
      </h2>
      <section className="my-16 w-2/3 m-auto">
        <ImageElt />
      </section>
    </main>
  );
};

export default Gallery;
