import type { Metadata } from 'next';
import Image from 'next/image';

export const metadata: Metadata = {
  title: "Galerie d'images | Ô Délices de Bertrand",
  description: 'Generated by create next app',
};

const Gallery = () => {
  return (
    <>
      <h2 className="mt-[15dvh] font-bold text-center uppercase text-3xl">Gallerie</h2>
      <main className="">
        <div className="m-8 border-4 border-slate-600">
          <Image
            src="/assets/img/clafoutis-pommes.png"
            alt="clafoutis aux pommes"
            width={500}
            height={500}
          />
        </div>
        <div className="m-8 border-4 border-slate-600">
          <Image
            className='m-auto'
            src="/assets/img/clafoutis-pommes.png"
            alt="clafoutis aux pommes"
            width={500}
            height={500}
          />
        </div>
      </main>
    </>
  );
};

export default Gallery;
