import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Connection | Ô Délices de Bertrand',
  description: 'Generated by create next app',
};

const Login = () => {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-center uppercase text-3xl">Connexion</p>
    </div>
  );
};

export default Login;
