import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Inscription | Ô Délices de Bertrand',
  description: 'Generated by create next app',
};

const Signup = () => {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-center uppercase text-3xl">Inscription</p>
    </div>
  );
};

export default Signup;
